version: "3"

services:
  mongo:
    image: mongo:latest
    container_name: ${DB_CONTAINER_NAME}
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=${MONGO_DB}
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_DB_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_DB_PASSWORD}
  app:
    build: .
    container_name: ${CONTAINER_NAME}
    ports:
      - "8080:8080"
    volumes:
      - .:/go/src/